export enum Mode {
  AND = 'AND',
  RANGE = 'RANGE',
  INCREMENT = 'INCREMENT',
  NTH_WEEKDAY_OF_MONTH = 'NTH_WEEKDAY_OF_MONTH',
  EVERY = 'EVERY',
  LAST_DAY = 'LAST_DAY',
  LAST_DAY_WEEK = 'LAST_DAY_WEEK',
  LAST_NTH_DAY_WEEK = 'LAST_NTH_DAY_WEEK',
  DAYS_BEFORE_END_MONTH = 'DAYS_BEFORE_END_MONTH',
  NEAREST_WEEKDAY_OF_MONTH = 'NEAREST_WEEKDAY_OF_MONTH',
  NONE = 'NONE'
}
